POST http://localhost:3000/api/users 
Content-Type: application/json

{
    "name": "Bob",
    "email": "bob@gmail.com",
    "role": "admin"
}

### Users
GET http://localhost:3000/api/users
Cookie: better-auth.session_token=M6rrPTE4lQ6aeS4XjjiphXOrmyxBrTZF.QIvN2Tb0otYIZkVlB8xIqAnKNkXNzuz4iQrXarFkGQY%3D


###
PUT http://localhost:3000/api/users/ds8Uq6u16qJPibvqL5SZXNogRCkl7EbO
Content-Type: application/json

{
    "name": "Teste",
    "email": "outro.email@gmail.com",
    "role": "admin"
}

###
PATCH  http://localhost:3000/api/users/ds8Uq6u16qJPibvqL5SZXNogRCkl7EbO
Content-Type: application/json

{
    "role": "designer"
}

###
DELETE http://localhost:3000/api/users/id



### Posts
GET http://localhost:3000/api/posts

###
POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "title": "Meu segundo Post",
    "content": "Qualquer conteúdo aqui",
    "published": true
}